### PR TITLE
chore: bump oclif command & plugin help

### PR DESCRIPTION
**Pull request by RasPhilCo**

### CODE REVIEW

**Comment by ArchangelX360** [comment]
We are experiencing failure in production due to a dependency conflict on `chalk`.

Could we merge this as fast as possible?

**Comment by RasPhilCo** [comment]
superseded by #98

**Comment by RasPhilCo** [comment]
@ArchangelX360 released 1.7.10

**Comment by ArchangelX360** [comment]
Thank you will test that later today :pray:

**Pull request closed without merging**
