### PR TITLE
Remove `yarn`  from the dependencies, make it a devDependency

### PR DESCRIPTION
**Pull request by SConaway**
Yarn is listed as a dependency. This is breaking yarn for me, as any time I `yarn global add` anything, my yarn binary disappears. I use `brew` to install it, but it removes itself from brew.

The `@oclif/plugin-plugins` package has been installed as a dependency for me, so I can't just manually remove it. After a quick look through this code, I am not seeing any potential issues caused by switching this, but I don't know anything about this project.

### CODE REVIEW

**Comment by SConaway** [comment]
Sorry for the `Am idiot` commit. I'm using GitHub web, so I couldn't edit the commit

**Comment by SConaway** [comment]
Any chance of resolving this? It breaks `yarn` for me

**Comment by RasPhilCo** [comment]
None of us can reproduce this locally. Do you have reproduction steps?

**Comment by SConaway** [comment]
Yes:

```
$ brew install node yarn
$ yarn global add netlify-cli prettier
...
$ yarn global add @angular/cli
$ yarn
yarn not found / whatever message that causes
```

Regardless of whether or not it is reproducible on the machines you guys use, I think that requiring a package manager is not acceptable for something that gets installed globally. Additionally, what if someone only uses node? This will install yarn for them. I'm not seeing the purpose of requiring `yarn` in this package anyway, but I owe this to a lack of familiarity with your codebase.

**Comment by RasPhilCo** [comment]
Interesting! Unfortunately, this is an issue with brew & yarn and has nothing to do with oclif. You can install via npm `$ npm install -g yarn` & `$ npm install -g netlify-cli` and not have any issues.

**Comment by SConaway** [comment]
Fair enough. So is this PR getting closed?

**Comment by RasPhilCo** [comment]
Was awaiting your response, but yes. Feel free to close it or if I don't hear back from you in a few days I can.

**Pull request closed without merging**
